### ISSUE TITLE
Doesn't show up in HACS

### ISSUE THREAD

**Issue by HVR88** [schmittx/home-assistant-eero#29]
Not sure if I'm missing something, but nothing "eero" related shows up in HACS when adding integration (repos)

Running current HASSIO and up-to-date HACS

The current version of HA/HACS is no longer anything like 3+ years ago which is all that's covered in various docs. No "settings" or other tabs any longer, etc. Adding repos via the HACS "integrations" lists a total of 998 available, but nothing eero.

**Comment by applegeeks** [comment]
tbh, this integration never worked for me and kept getting error's during initial setup at integration.

I ended up getting home assistant to retrieve eero data for my automations ( sense when someone is connected to wifi or not) by using this aged old repo (but still works wonderfully).

https://github.com/jrlucier/eero_tracker

**Comment by HVR88** [comment]
Unfortunately that other repo also isn't listed in HACS. Was it when you installed or did you do it manually?

**Comment by applegeeks** [comment]
Yes. it has be manual. 
you can doownload the repo through hacs but the rest of the configuration needs to be done manual and you can't enable it easily via the integration gui.

requires configuration.yaml changes.

ie. once downloaded. just added these configs based on my network.
```
## eero_tracker
device_tracker:
  - platform: eero_tracker
    consider_home: 60
    only_networks:
      - <insert-network-id>
    interval_seconds: 30
    only_wireless: true
```
